---

Organizations:
- &OrdererOrg
  Name: OrdererOrg
  ID: OrdererMSP
  MSPDir: cli/peers/ordererOrganizations/orderer-org/msp

- &BdsOrg
  Name: BdsOrgMSP
  ID: BdsOrgMSP
  MSPDir: cli/peers/peerOrganizations/bds-org/msp
  AnchorPeers:
  - Host: bds-peer
    Port: 7051

- &TraderOrg
  Name: TraderOrgMSP
  ID: TraderOrgMSP
  MSPDir: cli/peers/peerOrganizations/trader-org/msp
  AnchorPeers:
  - Host: trader-peer
    Port: 7051

- &CcqOrg
    Name: CcqOrgMSP
    ID: CcqOrgMSP
    MSPDir: cli/peers/peerOrganizations/ccq-org/msp
    AnchorPeers:
    - Host: ccq-peer
      Port: 7051

Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
  - orderer0:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:

Application: &ApplicationDefaults
  Organizations:

Profiles:
  ThreeOrgsGenesis:

    Orderer:
      <<: *OrdererDefaults
      Organizations:
      - *OrdererOrg
    Consortiums:
      RealEstateConsortium:
        Organizations:
        - *BdsOrg
        - *TraderOrg
        - *CcqOrg
  ThreeOrgsChannel:

    Consortium: RealEstateConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
      - *BdsOrg
      - *TraderOrg
      - *CcqOrg


