---
Profiles:
  FourOrgsGenesis:

    Orderer:
      <<: *OrdererDefaults
      Organizations:
      - *OrdererOrg
    Consortiums:
      RealEstateConsortium:
        Organizations:
        - *RealEstateOrg
        - *TraderOrg
        - *RegulatorOrg
  FourOrgsChannel:

    Consortium: RealEstateConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
      - *RealEstateOrg
      - *TraderOrg
      - *RegulatorOrg

Organizations:
- &OrdererOrg
  Name: OrdererOrg
  ID: OrdererMSP
  MSPDir: cli/peers/ordererOrganizations/orderer-org/msp

- &RealEstateOrg
  Name: RealEstateOrgMSP
  ID: RealEstateOrgMSP
  MSPDir: cli/peers/peerOrganizations/realestate-org/msp


  AnchorPeers:
  - Host: realestate-peer
    Port: 7051
- &TraderOrg
  Name: TraderOrgMSP
  ID: TraderOrgMSP
  MSPDir: cli/peers/peerOrganizations/trader-org/msp

  AnchorPeers:
  - Host: trader-peer
    Port: 7051
- &RegulatorOrg
    Name: RegulatorOrgMSP
    ID: RegulatorOrgMSP
    MSPDir: cli/peers/peerOrganizations/regulator-org/msp
    AnchorPeers:
    - Host: regulator-peer
      Port: 7051

Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
  - orderer0:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:

Application: &ApplicationDefaults
  Organizations:





