OrdererOrgs:
  - Name: OrdererOrg
    Domain: orderer-org
    CommonName: orderer-org
    Specs:
      - Hostname: orderer0
        CommonName: "{{.Hostname}}"
PeerOrgs:
  - Name: BdsOrg
    Domain: bds-org
    Specs:
      - Hostname: bds-peer
        CommonName: "{{.Hostname}}"
  - Name: TraderOrg
    Domain: trader-org
    Specs:
      - Hostname: trader-peer
        CommonName: "{{.Hostname}}"
  - Name: CcqOrg
    Domain: ccq-org
    Specs:
      - Hostname: ccq-peer
        CommonName: "{{.Hostname}}"
