version: '2'

networks:
  trit:

services:
  realestate-ca:
    container_name: realestate-ca
    extends:
      file: ./ca-base.yaml
      service: ca-base
    image: realestate-ca
    ports:
    - 7054:7054
    networks:
      - trit

  trader-ca:
    container_name: trader-ca
    extends:
      file: ./ca-base.yaml
      service: ca-base
    image: trader-ca
    ports:
    - 9054:7054
    networks:
      - trit

  regulator-ca:
    container_name: regulator-ca
    extends:
      file: ./ca-base.yaml
      service: ca-base
    image: regulator-ca
    ports:
    - 10054:7054
    networks:
      - trit

  orderer0:
    container_name: orderer0
    image: orderer
    environment:
    - ORDERER_GENERAL_LOGLEVEL=debug
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_GENESISMETHOD=file
    - ORDERER_GENERAL_GENESISFILE=/orderer/crypto/genesis.block
    - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    - ORDERER_GENERAL_LOCALMSPDIR=/orderer/crypto/msp
    - ORDERER_GENERAL_TLS_ENABLED=true
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/orderer/crypto/tls/server.key
    - ORDERER_GENERAL_TLS_CERTIFICATE=/orderer/crypto/tls/server.crt
    - ORDERER_GENERAL_TLS_ROOTCAS=[/orderer/crypto/tls/ca.crt]
    working_dir: /orderer
    command: orderer
    ports:
    - 7050:7050
    depends_on:
    - realestate-ca
    - trader-ca
    - regulator-ca
    networks:
      - trit

  realestate-peer:
    container_name: realestate-peer
    extends:
      file: ./peer-base.yaml
      service: peer-base
    image: realestate-peer
    environment:
    - CORE_PEER_ID=realestate-peer
    - CORE_PEER_ADDRESS=realestate-peer:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=realestate-peer:7051
    - CORE_PEER_LOCALMSPID=RealEstateOrgMSP
    ports:
    - 7051:7051
    - 7053:7053
    depends_on:
    - orderer0
    networks:
      - trit

  trader-peer:
    container_name: trader-peer
    extends:
      file: ./peer-base.yaml
      service: peer-base
    image: trader-peer
    environment:
    - CORE_PEER_ID=trader-peer
    - CORE_PEER_ADDRESS=trader-peer:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=trader-peer:7051
    - CORE_PEER_LOCALMSPID=TraderOrgMSP
    ports:
    - 9051:7051
    - 9053:7053
    depends_on:
    - orderer0
    - realestate-peer
    networks:
      - trit

  regulator-peer:
    container_name: regulator-peer
    extends:
      file: ./peer-base.yaml
      service: peer-base
    image: regulator-peer
    environment:
    - CORE_PEER_ID=regulator-peer
    - CORE_PEER_ADDRESS=regulator-peer:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=regulator-peer:7051
    - CORE_PEER_LOCALMSPID=RegulatorOrgMSP
    ports:
    - 10051:7051
    - 10053:7053
    depends_on:
    - orderer0
    - realestate-peer
    - trader-peer
    networks:
      - trit
  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=regulator-peer:7051
      - CORE_PEER_LOCALMSPID=RegulatorOrgMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/peer/crypto/peerOrganizations/regulator-org/peers/regulator-peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/peer/crypto/peerOrganizations/regulator-org/peers/regulator-peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/peer/crypto/peerOrganizations/regulator-org/peers/regulator-peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/peer/crypto/peerOrganizations/regulator-org/users/Admin@regulator-org/msp
    working_dir: /opt/gopath/
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./cli/chaincode/:/opt/gopath/src/github.com/chaincode
      - ./cli/crypto:/opt/gopath/peer/crypto/
      - ./cli/scripts:/opt/gopath/scripts/
      - ./cli/channel-artifacts:/opt/gopath/channel-artifacts
    depends_on:
    - orderer0
    - realestate-peer
    - trader-peer
    - regulator-peer
    networks:
      - trit


