version: '3.4'

networks:
  trit:
    external:
      name: trit


services:
  ccq-ca:
    image: hyperledger/fabric-ca:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 70054:7054
    volumes:
      - /var/run/:/host/var/run/
      - ./ccqCA/:/ca/
    environment:
      - FABRIC_CA_HOME=/ca
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=trit
    command: fabric-ca-server start
    networks:
      trit:
        aliases:
          - ccq-ca

  ccq-couchdb:
    container_name: ccq-couchdb
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=  
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      # placement:
      #     constraints:
      #         - node.hostname == $ORG1_HOSTNAME
    ports:
    - 5984:5984
    networks:
      bymn:
        aliases:
          - ccq-couchdb

  ccq-peer:
    hostname: ccq-peer
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=ccq-couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=

      - CORE_PEER_ID=ccq-peer
      - CORE_PEER_ADDRESS=ccq-peer:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=ccq-peer:7051
      - CORE_PEER_LOCALMSPID=CcqOrgMSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=trit
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_MSPCONFIGPATH=/peer/crypto/msp
      - CORE_PEER_TLS_CERT_FILE=/peer/crypto/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/peer/crypto/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/peer/crypto/tls/ca.crt
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    ports:
      - 70051:7051
      - 70053:7053
    working_dir: /peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./ccqPeer/crypto:/peer/crypto
    networks:
      trit:
        aliases:
          - ccq-peer



  cli:
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=ccq-peer:7051
      - CORE_PEER_LOCALMSPID=CcqOrgMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/peer/crypto/peerOrganizations/ccq-org/peers/ccq-peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/peer/crypto/peerOrganizations/ccq-org/peers/ccq-peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/peer/crypto/peerOrganizations/ccq-org/peers/ccq-peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/peer/crypto/peerOrganizations/ccq-org/users/Admin@ccq-org/msp
    working_dir: /opt/gopath/
    command: sleep 3600
    volumes:
      - /var/run/:/host/var/run/
      - ./cli/chaincode/:/opt/gopath/src/github.com/chaincode
      - ./cli/crypto:/opt/gopath/peer/crypto/
      - ./cli/scripts:/opt/gopath/scripts/
      - ./cli/channel-artifacts:/opt/gopath/channel-artifacts
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      trit:
        aliases:
          - cli


