version: '3.4'

networks:
  revex:
    external:
      name: revex

services:
  bds-ca:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/ca
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=revex
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 30054:7054
    volumes:
      - /var/run/:/host/var/run/
      - ./bdsCA/:/ca/
    command: fabric-ca-server start
    networks:
      revex:
        aliases:
          - bds-ca

  bds-couchdb:
    container_name: bds-couchdb
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=  
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      # placement:
      #     constraints:
      #         - node.hostname == $ORG1_HOSTNAME
    ports:
    - 5984:5984
    networks:
      revex:
        aliases:
          - bds-couchdb

  bds-peer:
    image: hyperledger/fabric-peer:latest
    hostname: bds-peer
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=bds-couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=

      - CORE_PEER_ID=bds-peer
      - CORE_PEER_ADDRESS=bds-peer:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=bds-peer:7051
      - CORE_PEER_LOCALMSPID=BdsOrgMSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=revex
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_MSPCONFIGPATH=/peer/crypto/msp
      - CORE_PEER_TLS_CERT_FILE=/peer/crypto/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/peer/crypto/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/peer/crypto/tls/ca.crt
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    ports:
      - 30051:7051
      - 30053:7053
    working_dir: /peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./bdsPeer/crypto:/peer/crypto
    networks:
      revex:
        aliases:
          - bds-peer



