version: '3.4'

networks:
  trit:
    external:
      name: trit


services:
  regulator-ca:
    image: hyperledger/fabric-ca:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 10054:7054
    volumes:
      - /var/run/:/host/var/run/
      - ./regulatorCA/:/ca/
    environment:
      - FABRIC_CA_HOME=/ca
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=trit
    command: fabric-ca-server start
    networks:
      trit:
        aliases:
          - regulator-ca

  regulator-peer:
    hostname: regulator-peer
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_PEER_ID=regulator-peer
      - CORE_PEER_ADDRESS=regulator-peer:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=regulator-peer:7051
      - CORE_PEER_LOCALMSPID=RegulatorOrgMSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=trit
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_MSPCONFIGPATH=/peer/crypto/msp
      - CORE_PEER_TLS_CERT_FILE=/peer/crypto/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/peer/crypto/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/peer/crypto/tls/ca.crt
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    ports:
      - 10051:7051
      - 10053:7053
    working_dir: /peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./regulatorPeer/crypto:/peer/crypto
    networks:
      trit:
        aliases:
          - regulator-peer



  cli:
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=regulator-peer:7051
      - CORE_PEER_LOCALMSPID=RegulatorOrgMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/peer/crypto/peerOrganizations/regulator-org/peers/regulator-peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/peer/crypto/peerOrganizations/regulator-org/peers/regulator-peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/peer/crypto/peerOrganizations/regulator-org/peers/regulator-peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/peer/crypto/peerOrganizations/regulator-org/users/Admin@regulator-org/msp
    working_dir: /opt/gopath/
    command: sleep 3600
    volumes:
      - /var/run/:/host/var/run/
      - ./cli/chaincode/:/opt/gopath/src/github.com/chaincode
      - ./cli/crypto:/opt/gopath/peer/crypto/
      - ./cli/scripts:/opt/gopath/scripts/
      - ./cli/channel-artifacts:/opt/gopath/channel-artifacts
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      trit:
        aliases:
          - cli


